### ISSUE TITLE
@pure decorator potentially dangerous?

### ISSUE THREAD

**Issue by gcanti** [buildo/revenge#17]
"pure" name is misleading: it could be applied to a component which is not pure. the decorator simply states that the component will be optimized with a default `shouldComponentUpdate` method relying on references

**Comment by gabro** [comment]
Minor concern: `@optimized` suggests a benefit, but it's not clear in the requirements.
At least with `@pure` you were hinted that the component should've been "pure", i.e. depending exclusively on an (immutable) set of input (i.e. the props)

As I understand it, there are a few caveats for using it without shooting yourself in a foot, namely:
- no mutable props
- no `RouteHandler`

others?

Do we have any way of asserting those away?

**Comment by gcanti** [comment]
- no mutable props
- no RouteHandler
- **no mutable state**

the more I think about this decorator the more I find it dangerous...

**Comment by gabro** [comment]
It's potentially dangerous, but the design encourages the use of tcomb structs.
I'm fine with this, if we state the requirements clearly
