### ISSUE TITLE
is @autobound really useful?

### ISSUE THREAD

**Issue by gcanti** [buildo/revenge#20]
Reading the code of autobound **I noticed that the method seems attached to the instance, not to the prototype** ... so instead of

``` js
import { autobound } from 'web-framework';

class Wrapper extends React.Component {

  @autobound
  method() {
    console.log(this.props.name);
  }

  render() {
    return <Wrapped method={this.method} />;
  }

}
```

yesterday @gabro suggested something like this

``` js
class Wrapper extends React.Component {

  method = () => console.log(this.props.name);

  render() {
    return <Wrapped method={this.method} />;
  }

}
```

**Comment by gabro** [comment]
well, if that's the case...
no way of attaching it to the prototype? And also, what's the impact of having it on the instance?

gabriele
~ buildo
