### ISSUE TITLE
rename build directory to lib and add an index.js file

### ISSUE THREAD

**Issue by gcanti** [buildo/revenge#3]
I think it's a standard to provide a ready to go package on npm:

``` sh
src       # ES6
lib       # transpiled files (ES5)
index.js  # npm package entry point
```

**Comment by giogonzo** [comment]
:+1:

On Tue, Jun 2, 2015 at 4:26 PM, Giulio Canti notifications@github.com
wrote:

> I think it's a standard to provide a ready to go package on npm:
> 
> src       # ES6
> lib       # transpiled files (ES5)
> index.js  # npm package entry point
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/buildo/web-framework/issues/3.

## 

Giovanni
~ buildo

**Comment by gcanti** [comment]
ops.. there's already an index.js file in src. The additional `root/index.js` file is useless. Pointing to `"main": "lib/index.js"` in package.json is enough

**Comment by giogonzo** [comment]
Yup, but I think anyway that `lib` instead of `build` is sort of a
convention

On Tue, Jun 2, 2015 at 4:43 PM, Giulio Canti notifications@github.com
wrote:

> ops.. there's already an index.js file in src. The additional
> root/index.js file is useless. Pointing to "main": "lib/index.js" in
> package.json is enough
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/buildo/web-framework/issues/3#issuecomment-107977274.

## 

Giovanni
~ buildo

**Comment by gcanti** [comment]
> `lib` instead of `build` is sort of a convention

:+1:

**Comment by gabro** [comment]
dist?

gabriele
~ buildo

**Comment by gcanti** [comment]
AFAIK `dist` is for minimized files and/or browser distributions
`lib` should be the standard on npm

**Comment by gabro** [comment]
:+1:

gabriele
~ buildo
