### ISSUE TITLE
strip if (NODE_ENV != 'production') in preprocessing for prod builds

### ISSUE THREAD

**Issue by utaal** [buildo/revenge#50]

**Comment by giogonzo** [comment]
Not really a revenge issue :tongue: 
But yeas, I'll have a better look at this

**Comment by utaal** [comment]
where should this go? infra?

**Comment by giogonzo** [comment]
Yes, thanks

On Fri, Jul 31, 2015 at 12:25 PM, Andrea Lattuada notifications@github.com
wrote:

> where should this go? infra?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/buildo/revenge/issues/50#issuecomment-126636877.

## 

Giovanni
~ buildo

**Comment by utaal** [comment]
Moved to https://github.com/buildo/infra/issues/70
