### ISSUE TITLE
split into separate small repos and deprecate this

### ISSUE THREAD

**Issue by giogonzo** [buildo/revenge#97]
## requirements
- publish `react-skinnable` (maybe `contains` template)
  and maybe `react-pure` (or use any of the available equivalent)
- deprecate this (update readme)

**Comment by FrancescoCioria** [comment]
@giogonzo still valid? we could begin in parallel with moving the two decorators in two separate repos but keep `revenge` active

**Comment by giogonzo** [comment]
Yes, we could!

> and maybe react-pure (or use any of the available equivalent)

About this, probably better to start with our own code to avoid any breakage?

**Comment by FrancescoCioria** [comment]
Yes, I would use our own decorator as the logic is very simple (so we can also _opinionate_ it if we need)

**Comment by FrancescoCioria** [comment]
I created two repos for `@skinnable` and `@pure`:
- https://github.com/buildo/react-skinnable
- https://github.com/buildo/react-pure

The relative libraries are already published on `npm` as:
- `react-skinnable`
- `buildo-react-pure`

**Comment by giogonzo** [comment]
looking good!

Note that the very simple `contains` function (https://github.com/buildo/revenge#skinnablecontainscomponent / https://github.com/buildo/revenge/blob/master/src/contains.js) is currently heavily used by `container`s (https://github.com/buildo/react-container) on LOL and other projects.

We should probably move it too?

**Comment by FrancescoCioria** [comment]
@giogonzo have a look at this PR: https://github.com/buildo/react-skinnable/pull/2
